// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("CMP6090")>]
[<assembly: AssemblyProductAttribute("CMP6090")>]
[<assembly: AssemblyDescriptionAttribute("CMP6090")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "CMP6090"
    let [<Literal>] AssemblyProduct = "CMP6090"
    let [<Literal>] AssemblyDescription = "CMP6090"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
